export const LANGUAGE_OPTIONS = [
  "English",
  "English (UK)",
  "English (US)",
  "English (EU)",
  "English (North American accent)",
  "English (RoW)",
  "Spanish",
  "Spanish (Mexico)",
  "Spanish (Spain)",
  "Portuguese",
  "Portuguese (Brazil)",
  "Portuguese (Portugal)",
  "Arabic",
  "Arabic (MENA)",
  "Arabic (Middle East)",
  "Arabic (Saudi Arabia)",
  "Arabic (South Africa)",
  "Arabic (RoW)",
  "French",
  "German",
  "Italian",
  "Russian",
  "Ukrainian",
  "Polish",
  "Romanian",
  "Slovak",
  "Czech",
  "Bulgarian",
  "Greek",
  "Dutch",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Turkish",
  "Azerbaijani",
  "Bengali",
  "Bengali (Bangladesh)",
  "Bengali (West Bengal, India)",
  "Catalan",
  "Hindi",
  "Urdu",
  "Pashto",
  "Nepali",
  "Burmese",
  "Khmer",
  "Thai",
  "Vietnamese",
  "Indonesian",
  "Malay",
  "Filipino / Tagalog",
  "Japanese",
  "Korean",
  "Swahili",
  "Swahili (Tanzania)",
  "Swahili (Africa)",
  "Afrikaans",
  "Hebrew",
  "Other",
  "Unknown",
] as const

export const SKILL_TASK_TYPE_OPTIONS = [
  "LLM Response Evaluation",
  "LLM Response Ranking",
  "LLM Safety Evaluation",
  "LLM Helpfulness Evaluation",
  "LLM Factuality Evaluation",
  "LLM Hallucination Evaluation",
  "LLM Red Teaming",
  "Prompt Evaluation",
  "Prompt Writing",
  "SFT Data Annotation",
  "RLHF Annotation",
  "Preference Ranking",
  "Golden Answer Writing",
  "Rubric Writing",
  "Search Relevance Evaluation",
  "Search Quality Evaluation",
  "Ads Quality Evaluation",
  "Content Moderation",
  "Trust & Safety Labeling",
  "Policy Violation Labeling",
  "Toxicity Evaluation",
  "Hate Speech Evaluation",
  "Sensitive Content Evaluation",
  "Translation",
  "Translation Review",
  "Localization",
  "Localization QA",
  "Cultural Adaptation",
  "Terminology Review",
  "Linguistic QA",
  "Transcription",
  "ASR Transcription",
  "ASR Validation",
  "Audio Annotation",
  "Speech Data Collection",
  "TTS Evaluation",
  "Voice Quality Evaluation",
  "OCR Annotation",
  "OCR Validation",
  "Image Annotation",
  "Image Caption Evaluation",
  "Video Annotation",
  "Video Understanding Evaluation",
  "Multimodal Evaluation",
  "Data QA",
  "Data Cleaning",
  "Data Collection",
  "Web Research",
  "Website Collection",
  "Local Website Evaluation",
  "Resume Screening",
  "Interview Evaluation",
  "Other",
] as const

export const EDUCATION_OPTIONS = [
  "High School",
  "Associate Degree",
  "Bachelor’s Degree",
  "Master’s Degree",
  "PhD / Doctorate",
  "Other",
  "Unknown",
] as const

export const PROFESSIONAL_DOMAIN_OPTIONS = [
  "Linguistics",
  "Translation / Localization",
  "Education",
  "Computer Science / AI",
  "Data Annotation",
  "Search Evaluation",
  "Content Moderation / Trust & Safety",
  "Marketing / Media",
  "Finance / Business",
  "Law / Legal",
  "Healthcare / Medical",
  "E-commerce",
  "Gaming",
  "Social Media",
  "Customer Support",
  "General",
  "Other",
  "Unknown",
] as const
